{{ if .Values.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: smp-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
    - http:
        paths:
  {{ range $context := .Values.ingress.context_paths }}
          - path: {{ $context.path }}
            pathType: Prefix
            backend:
              service:
                name: hello-world-{{ $context.name }}
                port:
                  number: 8000
  {{ end }}
  {{ end }}